### ISSUE TITLE
Create a Rest-ful API 

### ISSUE THREAD

**Issue by A1exLemesios** [A1exLemesios/api-training#1]
#### Todos :
- [x] Create 5 endpoints which will respond just by sending the requests parameters back 
- [x] Link the API controller with an sql db
- [x] Finish the endpoints 
- [x] Create another table (brands one to many relation)
- [ ] Research for swagger based testing (stackoverflow question , best practise indicated way .how to make a lightwieight test that is still ok )
- [ ]  Mocks on swagger . How do they work ?

Monday 17/10
- [ ] Code styling practise (eslint etc)
